version: "3"

services:
   php:
      build: ./php
      depends_on:
         - sql
      env_file:
         - ./docker-compose.env
      ports:
         - 8081:80
      volumes:
         - ./php/Classes:/var/www/Classes
         - ./php/public_html:/var/www/public_html
         - ./php/lib:/var/www/lib
   app:
      build: ./app
      depends_on:
         - php
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
         - /docker-volumes/pwp/etc/letsencrypt/live/odysseyofultimate.com/fullchain.pem:/etc/letsencrypt/live/odysseyofultimate.com/fullchain.pem
         - /docker-volumes/pwp/etc/letsencrypt/live/odysseyofultimate.com/privkey.pem:/etc/letsencrypt/live/odysseyofultimate.com/privkey.pem

   sql:
      build: ./sql
      volumes:
         - smash-sql:/var/lib/mysql
      env_file:
         - ./docker-compose.env
      command: --default-authentication-plugin=mysql_native_password
volumes:
   smash-sql: